name: farmer_app
description: "Farmer App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  geolocator: ^13.0.2
  http: ^1.3.0
  flutter_dotenv: ^5.2.1
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  shared_preferences: ^2.5.2
  google_generative_ai: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images.jpg
    - .env
    - .env.sample